// Code generated by protoc-gen-go. DO NOT EDIT.
// source: src/api/message/contract/v1/contract.proto

package v1

import (
	fmt "fmt"
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	proto "github.com/golang/protobuf/proto"
	v1 "github.com/hamed-yousefi-tb/envoyproxy-example/pkg/api/message/common/v1"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type FilterColumns int32

const (
	FilterColumns_NO_FILTER FilterColumns = 0
	FilterColumns_NAME      FilterColumns = 1
)

var FilterColumns_name = map[int32]string{
	0: "NO_FILTER",
	1: "NAME",
}

var FilterColumns_value = map[string]int32{
	"NO_FILTER": 0,
	"NAME":      1,
}

func (x FilterColumns) String() string {
	return proto.EnumName(FilterColumns_name, int32(x))
}

func (FilterColumns) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_df63c90e20ac3c64, []int{0}
}

type Contract struct {
	Id                   *v1.UUID `protobuf:"bytes,1,opt,name=Id,proto3" json:"Id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`
	Content              []byte   `protobuf:"bytes,3,opt,name=Content,proto3" json:"Content,omitempty"`
	SignDate             []byte   `protobuf:"bytes,4,opt,name=SignDate,proto3" json:"SignDate,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Contract) Reset()         { *m = Contract{} }
func (m *Contract) String() string { return proto.CompactTextString(m) }
func (*Contract) ProtoMessage()    {}
func (*Contract) Descriptor() ([]byte, []int) {
	return fileDescriptor_df63c90e20ac3c64, []int{0}
}

func (m *Contract) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Contract.Unmarshal(m, b)
}
func (m *Contract) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Contract.Marshal(b, m, deterministic)
}
func (m *Contract) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Contract.Merge(m, src)
}
func (m *Contract) XXX_Size() int {
	return xxx_messageInfo_Contract.Size(m)
}
func (m *Contract) XXX_DiscardUnknown() {
	xxx_messageInfo_Contract.DiscardUnknown(m)
}

var xxx_messageInfo_Contract proto.InternalMessageInfo

func (m *Contract) GetId() *v1.UUID {
	if m != nil {
		return m.Id
	}
	return nil
}

func (m *Contract) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Contract) GetContent() []byte {
	if m != nil {
		return m.Content
	}
	return nil
}

func (m *Contract) GetSignDate() []byte {
	if m != nil {
		return m.SignDate
	}
	return nil
}

type GetContractsRequest struct {
	Page                 *v1.Pagination `protobuf:"bytes,1,opt,name=Page,proto3" json:"Page,omitempty"`
	Filter               *Filter        `protobuf:"bytes,2,opt,name=Filter,proto3" json:"Filter,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *GetContractsRequest) Reset()         { *m = GetContractsRequest{} }
func (m *GetContractsRequest) String() string { return proto.CompactTextString(m) }
func (*GetContractsRequest) ProtoMessage()    {}
func (*GetContractsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_df63c90e20ac3c64, []int{1}
}

func (m *GetContractsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetContractsRequest.Unmarshal(m, b)
}
func (m *GetContractsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetContractsRequest.Marshal(b, m, deterministic)
}
func (m *GetContractsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetContractsRequest.Merge(m, src)
}
func (m *GetContractsRequest) XXX_Size() int {
	return xxx_messageInfo_GetContractsRequest.Size(m)
}
func (m *GetContractsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetContractsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetContractsRequest proto.InternalMessageInfo

func (m *GetContractsRequest) GetPage() *v1.Pagination {
	if m != nil {
		return m.Page
	}
	return nil
}

func (m *GetContractsRequest) GetFilter() *Filter {
	if m != nil {
		return m.Filter
	}
	return nil
}

type Filter struct {
	Column               FilterColumns      `protobuf:"varint,1,opt,name=Column,proto3,enum=trialblaze.api.contracts.message.contract.v1.FilterColumns" json:"Column,omitempty"`
	Value                string             `protobuf:"bytes,2,opt,name=Value,proto3" json:"Value,omitempty"`
	Operation            v1.FilterOperation `protobuf:"varint,3,opt,name=Operation,proto3,enum=trialblaze.api.contracts.message.v1.FilterOperation" json:"Operation,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *Filter) Reset()         { *m = Filter{} }
func (m *Filter) String() string { return proto.CompactTextString(m) }
func (*Filter) ProtoMessage()    {}
func (*Filter) Descriptor() ([]byte, []int) {
	return fileDescriptor_df63c90e20ac3c64, []int{2}
}

func (m *Filter) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Filter.Unmarshal(m, b)
}
func (m *Filter) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Filter.Marshal(b, m, deterministic)
}
func (m *Filter) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Filter.Merge(m, src)
}
func (m *Filter) XXX_Size() int {
	return xxx_messageInfo_Filter.Size(m)
}
func (m *Filter) XXX_DiscardUnknown() {
	xxx_messageInfo_Filter.DiscardUnknown(m)
}

var xxx_messageInfo_Filter proto.InternalMessageInfo

func (m *Filter) GetColumn() FilterColumns {
	if m != nil {
		return m.Column
	}
	return FilterColumns_NO_FILTER
}

func (m *Filter) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

func (m *Filter) GetOperation() v1.FilterOperation {
	if m != nil {
		return m.Operation
	}
	return v1.FilterOperation_LIKE
}

func init() {
	proto.RegisterEnum("trialblaze.api.contracts.message.contract.v1.FilterColumns", FilterColumns_name, FilterColumns_value)
	proto.RegisterType((*Contract)(nil), "trialblaze.api.contracts.message.contract.v1.Contract")
	proto.RegisterType((*GetContractsRequest)(nil), "trialblaze.api.contracts.message.contract.v1.GetContractsRequest")
	proto.RegisterType((*Filter)(nil), "trialblaze.api.contracts.message.contract.v1.Filter")
}

func init() {
	proto.RegisterFile("src/api/message/contract/v1/contract.proto", fileDescriptor_df63c90e20ac3c64)
}

var fileDescriptor_df63c90e20ac3c64 = []byte{
	// 471 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x9c, 0x53, 0x4f, 0x6f, 0xd3, 0x30,
	0x14, 0x27, 0x6d, 0xd7, 0x3f, 0x1e, 0x1b, 0x95, 0xe1, 0x10, 0x8d, 0x0b, 0x1a, 0x12, 0xda, 0x26,
	0x62, 0xab, 0x85, 0x0b, 0xda, 0x69, 0xd9, 0x1f, 0x54, 0x69, 0x5d, 0x51, 0x60, 0x1c, 0x10, 0x08,
	0xb9, 0xed, 0x23, 0xb3, 0x48, 0xec, 0x10, 0x3b, 0xd1, 0xda, 0x23, 0x47, 0x3e, 0x0e, 0x5f, 0x87,
	0xaf, 0xc1, 0x69, 0x27, 0x5c, 0x27, 0x0d, 0x45, 0x13, 0x62, 0xec, 0xe6, 0xbc, 0xf7, 0x7e, 0xff,
	0xf4, 0x5e, 0xd0, 0x9e, 0x4a, 0x27, 0x94, 0x25, 0x9c, 0xc6, 0xa0, 0x14, 0x0b, 0x81, 0x4e, 0xa4,
	0xd0, 0x29, 0x9b, 0x68, 0x9a, 0xf7, 0xaa, 0x37, 0x49, 0x52, 0xa9, 0x25, 0x7e, 0xaa, 0x53, 0xce,
	0xa2, 0x71, 0xc4, 0xe6, 0x40, 0x0c, 0x84, 0x2c, 0xdb, 0x8a, 0x94, 0xe0, 0xaa, 0x42, 0xf2, 0xde,
	0xd6, 0x41, 0xc8, 0xf5, 0x45, 0x36, 0x36, 0xb5, 0x98, 0x82, 0xc8, 0xe5, 0xcc, 0x90, 0x5c, 0xce,
	0xa8, 0xa5, 0x9a, 0x78, 0x21, 0x08, 0x2f, 0x67, 0x11, 0x9f, 0x32, 0x0d, 0xf4, 0xda, 0xa3, 0x10,
	0xdc, 0x7a, 0x72, 0xdd, 0x5c, 0x1c, 0x4b, 0x51, 0x58, 0x5b, 0xbc, 0x8a, 0xb9, 0xed, 0xef, 0x0e,
	0x6a, 0x1f, 0x96, 0xd2, 0xf8, 0x05, 0xaa, 0x0d, 0xa6, 0xae, 0xf3, 0xc8, 0xd9, 0x59, 0xef, 0xef,
	0x92, 0x7f, 0x5a, 0xce, 0x7b, 0xe4, 0xfc, 0x7c, 0x70, 0x14, 0x18, 0x10, 0x7e, 0x88, 0x1a, 0x67,
	0x2c, 0x06, 0xb7, 0x66, 0xc0, 0x1d, 0xbf, 0x75, 0xe5, 0x37, 0xd2, 0x9a, 0xdb, 0x0f, 0x6c, 0x11,
	0xef, 0xa2, 0xd6, 0x42, 0x03, 0x84, 0x76, 0xeb, 0xa6, 0x7f, 0xd7, 0xbf, 0x67, 0xfa, 0xf3, 0x5a,
	0x77, 0x7a, 0xe5, 0xaf, 0xcd, 0xeb, 0xee, 0xcf, 0x7a, 0xb0, 0xec, 0xe3, 0xc7, 0xa8, 0xfd, 0x9a,
	0x87, 0xe2, 0xc8, 0x24, 0x71, 0x1b, 0x76, 0xb6, 0x55, 0xcc, 0x3a, 0x41, 0xd5, 0x58, 0x98, 0xbe,
	0xff, 0x12, 0xf4, 0xd2, 0xb7, 0x0a, 0xe0, 0x4b, 0x06, 0x4a, 0xe3, 0x21, 0x6a, 0xbc, 0x32, 0xc6,
	0xca, 0x04, 0xf4, 0x46, 0x09, 0x0c, 0x80, 0x0b, 0xa6, 0xb9, 0x14, 0x7e, 0xdb, 0xd8, 0xf9, 0xe6,
	0x2c, 0xa4, 0x2c, 0x0d, 0x3e, 0x45, 0xcd, 0x13, 0x1e, 0x69, 0x48, 0x6d, 0xaa, 0xf5, 0xfe, 0x73,
	0xf2, 0x3f, 0x5b, 0x24, 0x05, 0x36, 0x28, 0x39, 0xb6, 0x7f, 0x38, 0x4b, 0x3a, 0xfc, 0x01, 0x35,
	0x0f, 0x65, 0x94, 0xc5, 0xc2, 0x3a, 0xdd, 0xec, 0xef, 0xdf, 0x86, 0xb8, 0x60, 0x50, 0xd6, 0xf5,
	0x57, 0xeb, 0xba, 0x24, 0xc5, 0x0f, 0xd0, 0xda, 0x5b, 0x16, 0x65, 0xe5, 0x32, 0x82, 0xe2, 0x03,
	0xbf, 0x47, 0x9d, 0x51, 0x02, 0xa9, 0x8d, 0x6a, 0xd7, 0xb0, 0x79, 0x93, 0x40, 0x95, 0x5c, 0x85,
	0x5d, 0x11, 0xfc, 0x4d, 0xb8, 0xb7, 0x83, 0x36, 0xfe, 0xb0, 0x85, 0x37, 0x50, 0xe7, 0x6c, 0xf4,
	0xf1, 0x64, 0x70, 0xfa, 0xe6, 0x38, 0xe8, 0xde, 0xc1, 0x6d, 0x73, 0x1f, 0x07, 0xc3, 0xe3, 0xae,
	0xe3, 0x8f, 0xde, 0x0d, 0x57, 0xce, 0xfb, 0xc2, 0xdc, 0xc7, 0xd4, 0x9b, 0xc9, 0x4c, 0xc1, 0x27,
	0xee, 0xe9, 0xf1, 0xca, 0xbd, 0x7b, 0x70, 0xc9, 0xe2, 0x24, 0x02, 0x9a, 0x7c, 0x0e, 0xff, 0xf6,
	0x9f, 0xed, 0xe7, 0xbd, 0x71, 0xd3, 0x5e, 0xf2, 0xb3, 0x5f, 0x01, 0x00, 0x00, 0xff, 0xff, 0xac,
	0x81, 0x23, 0xf5, 0x90, 0x03, 0x00, 0x00,
}
